# Generated by Django 4.2.5 on 2023-12-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeldata', '0002_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
