# Generated by Django 4.2.5 on 2023-12-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeldata', '0005_sale_sale_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='qty_sold',
            field=models.IntegerField(),
        ),
    ]
